#!/usr/bin/env bash
#configures an Ubuntu server to resolve IP addresses
#sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
#sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

